import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState, useEffect } from 'react'
import styles from '../styles/Home.module.css'
import { getBlockFromTimestamp } from './api/hello'
import AreaChart from '../components/AreaChart'

type IBulkTransfer = {
  id: string,
  bulkCount: string,
  timestamp : string
}

const Home: NextPage = () => {
  const [isLoading, setIsLoading] = useState<boolean>(true)
  const [bulkTransfers, setBulkTransfers] = useState<Array<IBulkTransfer>>()
  
  useEffect(() => {
    const init = async () => {
      setBulkTransfers(await getBlockFromTimestamp())
    }
    init()
    setIsLoading(false)
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Human Protocol
        </h1>
        {bulkTransfers && <div>
          <AreaChart chartData={bulkTransfers} />
        </div>
        }
        <div className={styles.description}>
          <div>BulkTransfer Number: {bulkTransfers?.length}</div>
          {!isLoading && bulkTransfers && bulkTransfers.map((bulkTransfer) => {
            return (
              <ul key={bulkTransfer.id}>
                <li>ID: {bulkTransfer.id}</li>
                <li>BulkCount: {bulkTransfer.bulkCount}</li>
                <li>Timestamp: {bulkTransfer.timestamp}</li>
              </ul>
            )
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
